### ISSUE TITLE
After upgrade to Fedora 41 from 40 dnfdragora crashes while updating installed package cache

### ISSUE THREAD

**Issue by NochnTim** [manatools/dnfdragora#241]
Hi, 
After system upgrade to Fedora 41 dnfdragora exits on call-up with:

`UI Error: g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib64/python3.13/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.13/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 239, in GetPackages
    value = self.get_packages_ndsg(pkg_filter)
  File "/usr/lib/python3.13/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/dnfdaemon/server/__init__.py", line 408, in get_packages_ndsg
    pkgs = getattr(self.base.packages, pkg_filter)
AttributeError: 'NoneType' object has no attribute 'installed'
 (36) `

dnf5 in working like a charm in terminal and claims system is up-to-date.
dnf check resp. dnf clean all did not help.
Reinstalling dnf* did not solve the problem.

Is there anything I can do  to shed more light on the problem?

**Comment by anaselli** [comment]
I need to release the first "beta" for dnf5, by now you still need dnf4 and its dnfdaemon to use dnfdragora.

**Comment by NochnTim** [comment]
Ah, thanks for the quick response - than I will just be patient.
